name: todo_flutter2
description: A Todo app with sign-in, CRUD, tabs, filters, and responsive UI.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  google_sign_in: ^6.2.2
  flutter_svg: ^2.1.0

  # Optional enhancements
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  # ✅ No assets are declared anymore to avoid errors
  # assets:
  #   - assets/google_logo.svg
