// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz-jyDErpMsF4hxfe4LUtBk9zdvFZ6nlw',
    appId: '1:793584591605:web:bddd45619a9f4d6a961bbc',
    messagingSenderId: '793584591605',
    projectId: 'todoflutter2-58699',
    authDomain: 'todoflutter2-58699.firebaseapp.com',
    storageBucket: 'todoflutter2-58699.firebasestorage.app',
    measurementId: 'G-CV3K1BQGY8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmJMx5WCh0cQfqmxEiXNow85y6HkIqiCI',
    appId: '1:793584591605:android:f6d000f78d1c5e4c961bbc',
    messagingSenderId: '793584591605',
    projectId: 'todoflutter2-58699',
    storageBucket: 'todoflutter2-58699.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7u81cyEYB_mWwnujFuRRRAysz8cBVZ2g',
    appId: '1:793584591605:ios:b0110d1b084f4d08961bbc',
    messagingSenderId: '793584591605',
    projectId: 'todoflutter2-58699',
    storageBucket: 'todoflutter2-58699.firebasestorage.app',
    iosBundleId: 'com.example.todoFlutter2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7u81cyEYB_mWwnujFuRRRAysz8cBVZ2g',
    appId: '1:793584591605:ios:b0110d1b084f4d08961bbc',
    messagingSenderId: '793584591605',
    projectId: 'todoflutter2-58699',
    storageBucket: 'todoflutter2-58699.firebasestorage.app',
    iosBundleId: 'com.example.todoFlutter2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDz-jyDErpMsF4hxfe4LUtBk9zdvFZ6nlw',
    appId: '1:793584591605:web:ae44197a941867e1961bbc',
    messagingSenderId: '793584591605',
    projectId: 'todoflutter2-58699',
    authDomain: 'todoflutter2-58699.firebaseapp.com',
    storageBucket: 'todoflutter2-58699.firebasestorage.app',
    measurementId: 'G-WL5N42RGKH',
  );
}
